version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_DATABASE_URL=${POSTGRES_DATABASE_URL}
      - SUPABASE_API_KEY=${SUPABASE_API_KEY}
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_NAME=${MONGODB_NAME}
      - ROCKET_ADDRESS=0.0.0.0
    depends_on:
      - db
      - mongo

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_NAME}
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
